plugins {
    id 'war'
    id("org.gretty") version "4.1.6"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

group = 'ru.incubator'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.11.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.assertj:assertj-core:3.26.3'
    testImplementation 'org.mockito:mockito-core:5.14.2'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.14.2'
    testImplementation 'org.springframework:spring-test:6.2.1'

    implementation 'org.springframework:spring-orm:6.2.1'
    implementation 'org.freemarker:freemarker:2.3.33'
    implementation 'org.springframework:spring-context-support:6.2.1'
    implementation 'org.springframework:spring-orm:6.2.1'
    implementation 'com.h2database:h2:2.3.232'
    implementation 'org.springframework:spring-webmvc:6.2.1'
    implementation 'org.hibernate.orm:hibernate-core:6.6.4.Final'

    compileOnly 'jakarta.servlet:jakarta.servlet-api:6.1.0'

}

test {
    useJUnitPlatform()
}

tasks.register('buildAndCopyWarToApache', Copy) {
    from war // shortcut for createJar.outputs.files
    into "/opt/apache-tomcat-10.1.26/webapps"
    dependsOn(war)
}

