plugins {
    id 'java'
    id 'application'
}

group = 'ru.incubator'
version = 'unspecified'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

application {
    mainClass = 'ru.incubator.Main'
}

tasks.jar {
    manifest {
        attributes["Main-Class"] = "ru.incubator.Main"
    }
}